let briefcaseImages = [
	{
		category: "logos f1",
		namePrimary: "zooquillapampa",
		urlPrimary: "zooquillapampa.jpg",
		imagesSecondary: [
			{name: "zooquillapampa.jpg", url: "zooquillapampa.jpg"},
			{name: "cross", url: "cross.jpg"},
			{name: "abogados", url: "abogados.jpg"},
			{name: "powergym", url: "powergym.jpg"},
			{name: "apricot", url: "apricot.jpg"},
		],
	},
	{
		category: "identidad f1",
		namePrimary: "sebas tarjeta",
		urlPrimary: "sebastarjeta.jpg",
		imagesSecondary: [
			{name: "sebastarjeta.jpg", url: "sebastarjeta.jpg"},
			{name: "cross", url: "cross2.jpg"},
			{name: "fitness nutrition", url: "fitnessnutrition.jpg"},
			{name: "procope", url: "procope.jpg"},
			{name: "fitness nutrition", url: "fitnessnutrition2.jpg"},
		],
	},
	{
		category: "impresos f1",
		namePrimary: "volante esika",
		urlPrimary: "volanteesika.jpg",
		imagesSecondary: [
			{name: "volanteesika.jpg", url: "volanteesika.jpg"},
			{name: "triptico premios juntos", url: "tripticopremiosjuntos.jpg"},
			{name: "volante power gym", url: "volantepowergym.jpg"},
			{name: "room 21b", url: "room21b.jpg"},
			{name: "volante unica", url: "volanteunica.jpg"},
		],
	},
	{
		category: "miselaneo",
		namePrimary: "jehova dios hombre",
		urlPrimary: "jehovadioshombre.jpg",
		imagesSecondary: [
			{name: "jehovadioshombre.jpg", url: "jehovadioshombre.jpg"},
			{name: "taza", url: "taza.jpg"},
			{name: "tar", url: "tar.jpg"},
			{name: "cristo mujer", url: "cristomujer.jpg"},
			{name: "triptico esika", url: "tripticoesika.jpg"},
		],
	},
	{
		category: "nofound",
		namePrimary: "nofound",
		urlPrimary: "nofound.jpg",
		imagesSecondary: [{name: "nofound.jpg", url: "nofound.jpg"}],
	},
	{
		category: "web f2",
		namePrimary: "web",
		urlPrimary: "web.jpg",
		imagesSecondary: [
			{name: "web.jpg", url: "web.jpg"},
			{name: "web banco financiero", url: "2.jpg"},
			{name: "face mock", url: "facemock.jpg"},
			{name: "post valora", url: "postvalora.jpg"},
		],
	},
	{
		category: "prensa f2",
		namePrimary: "lebel lederm",
		urlPrimary: "lebellederm.jpg",
		imagesSecondary: [
			{name: "lebel lederm", url: "lebellederm.jpg"},
			{name: "brucke cy-zone", url: "bruckecy-zone.jpg"},
			{name: "esika reyna", url: "esikareyna.jpg"},
			{name: "lebel revista", url: "lebelchicarevista.jpg"},
			{name: "belcorp", url: "belcorp.jpg"},
		],
	},
	{
		category: "outdoor poster",
		namePrimary: "chica banner",
		urlPrimary: "chicabanner.jpg",
		imagesSecondary: [
			{name: "chica banner", url: "chicabanner.jpg"},
			{name: "afiche coqueto", url: "afichecoqueta.jpg"},
			{name: "banner esika", url: "banneresika.jpg"},
			{name: "banner scotiabank", url: "bannerscotiabank.jpg"},
			{name: "colgante banco", url: "colgantebanco.jpg"},
		],
	},
	{
		category: "outdoor banner",
		namePrimary: "outdoor banner",
		urlPrimary: "outdoorbanner.jpg",
		imagesSecondary: [
			{name: "outdoor banner", url: "outdoorbanner.jpg"},
			{name: "valla lebel", url: "vallalebel.jpg"},
			{name: "paradero dental", url: "paraderodental.jpg"},
			{name: "valla movil chico flip", url: "vallamovilchicoflip.jpg"},
			{name: "valla esika coqueto", url: "Vallaesikacoqueto.jpg"},
		],
	},
	{
		category: "identidad f3",
		namePrimary: "creative studio",
		urlPrimary: "creativestudio.jpg",
		imagesSecondary: [
			{name: "creative estudio", url: "creativestudio.jpg"},
			{name: "mac", url: "mac.jpg"},
			{name: "directo", url: "directo.jpg"},
			{name: "acuarius", url: "acuarius.jpg"},
			{name: "labok", url: "labok.jpg"},
		],
	},
	{
		category: "impresos f3",
		namePrimary: "pizza raul",
		urlPrimary: "pizzaraul.jpg",
		imagesSecondary: [
			{name: "pizza raul", url: "pizzaraul.jpg"},
			{name: "unica", url: "unica.jpg"},
			{name: "volante lebel", url: "volantelebel.jpg"},
			{name: "pizza raul", url: "pizzaraul2.jpg"},
			{name: "juguetes", url: "juguetes.jpg"},
		],
	},
	{
		category: "logo f4",
		namePrimary: "strong",
		urlPrimary: "strong.jpg",
		imagesSecondary: [
			{name: "strong", url: "strong.jpg"},
			{name: "barber shop sebas", url: "barbershopsebas.jpg"},
			{name: "body care", url: "bodycare.jpg"},
			{name: "cat dog", url: "catdog.jpg"},
			{name: "directo", url: "directo2.jpg"},
		],
	},
	{
		category: "nofound",
		namePrimary: "nofound",
		urlPrimary: "nofound.jpg",
		imagesSecondary: [{name: "nofound.jpg", url: "nofound.jpg"}],
	},
	{
		category: "outdoor banner f4",
		namePrimary: "vallanavidad",
		urlPrimary: "vallanavidad.jpg",
		imagesSecondary: [
			{name: "valla navidad", url: "vallanavidad.jpg"},
			{name: "panel lebel", url: "panellebel.jpg"},
			{name: "movil fary", url: "movilfary.jpg"},
			{name: "billboard bus", url: "billboardbus.jpg"},
			{name: "paradero", url: "paradero2.jpg"},
		],
	},
	{
		category: "impresos f5",
		namePrimary: "room21a",
		urlPrimary: "room21a.jpg",
		imagesSecondary: [
			{name: "room 21 a", url: "room21a.jpg"},
			{name: "juntos", url: "juntos.jpg"},
			{name: "gmo", url: "gmo.jpg"},
			{name: "volante pizza raul", url: "volantepizzaraul.jpg"},
			{name: "volante unica", url: "volanteunica2.jpg"},
		],
	},
	{
		category: "miselaneo f5",
		namePrimary: "cristo hombre",
		urlPrimary: "cristohombre2.jpg",
		imagesSecondary: [
			{name: "cristo hombre", url: "cristohombre2.jpg"},
			{name: "calendario eva", url: "calendarioeva.jpg"},
			{name: "bolsa esika", url: "bolsaesika.jpg"},
			{name: "rey mujer", url: "reymujer.jpg"},
			{name: "esika reyna", url: "esikareyna2.jpg"},
		],
	},
	{
		category: "web f5",
		namePrimary: "post valora",
		urlPrimary: "postvalora.jpg",
		imagesSecondary: [
			{name: "post valora", url: "postvalora2.jpg"},
			{name: "productos mac", url: "productosmac.jpg"},
			{name: "web nutricion", url: "webnutriciongym.jpg"},
			{name: "web banco financiero", url: "webbancofinanciero2.jpg"},
		],
	},
	{
		category: "prensa f5",
		namePrimary: "prensa marko",
		urlPrimary: "prensamarko.jpg",
		imagesSecondary: [
			{name: "prensa marko", url: "prensamarko.jpg"},
			{name: "libro macroeconomica andina", url: "libromacroeconomicaandina.jpg"},
			{name: "revista rose rose", url: "revistaroserose.jpg"},
			{name: "revista portada cosas", url: "revistaportadacosas.jpg"},
			{name: "revista lebel", url: "revistalebel.jpg"},
		],
	},
	{
		category: "outdoor banner f6",
		namePrimary: "bus stop",
		urlPrimary: "busstop.jpg",
		imagesSecondary: [
			{name: "bus stop", url: "busstop.jpg"},
			{name: "valla doble cy-zone", url: "valladoblecyzone.jpg"},
			{name: "bus stop muay thai", url: "busstopmuaythai.jpg"},
			{name: "bus stop esika", url: "busstopesika.jpg"},
			{name: "paneles master class", url: "panelesmasterclass.jpg"},
		],
	},
	{
		category: "outdoor poster f6",
		namePrimary: "mise scotiabank",
		urlPrimary: "misescotiabank.jpg",
		imagesSecondary: [
			{name: "mise scotiabank", url: "misescotiabank.jpg"},
			{name: "panel unica, cyzone", url: "panelunicacyzone.jpg"},
			{name: "afiche cy-zone quierete", url: "afichecy-zonequierete.jpg"},
			{name: " banderola look cy-zone", url: " banderolalookcy-zone.jpg"},
			{name: "banner esika bravio", url: "banneresikabravio.jpg"},
		],
	},
	{
		category: "nofound",
		namePrimary: "nofound",
		urlPrimary: "nofound.jpg",
		imagesSecondary: [{name: "nofound.jpg", url: "nofound.jpg"}],
	},
];
